#!/usr/bin/env bash
# surrogate
# primary library

# get config file(s)
for config in $(ls /etc/surrogate//);
	do
		source /etc/surrogate/$config
	done

source $my_root/lib/rotate

function determine_full_backup_path(){
  # determine the location of todays backup (for retention)
  if [[ `date +%d` == "01" ]]; 
    then
        full_backup_path="$backup_directory/monthly/full-$now"
  elif [[ `date +%u` == "7" ]];
    then
        full_backup_path="$backup_directory/weekly/full-$now"
  else
        #full_backup_path="$backup_directory/daily/`LC_TIME=en_US date +%A`/full-$now"
	full_backup_path="$backup_directory/daily/`LC_TIME=en_US date +%A`/"
  fi
}
# fin
